In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'property_id':[1,2,3,4,5],
    'price':[250000,300000,150000,400000,350000],
    'size_sqft':[1500,2000,1200,2500,1800],
    'date_listed':['2023-01-15','2023-02-20','2023-03-10','2023-04-05','2023-05-01'],
    'year_built':[1990,2005,1980,2010,2000]
}

In [3]:
df = pd.DataFrame(data)

df

   property_id   price  size_sqft date_listed  year_built
0            1  250000       1500  2023-01-15        1990
1            2  300000       2000  2023-02-20        2005
2            3  150000       1200  2023-03-10        1980
3            4  400000       2500  2023-04-05        2010
4            5  350000       1800  2023-05-01        2000

In [4]:
# Feature Engineering

df['price_per_sqft'] = df['price'] / df['size_sqft']

df['price_per_sqft'] = df['price_per_sqft'].round(2)

df

   property_id   price  size_sqft date_listed  year_built  price_per_sqft
0            1  250000       1500  2023-01-15        1990          166.67
1            2  300000       2000  2023-02-20        2005          150.00
2            3  150000       1200  2023-03-10        1980          125.00
3            4  400000       2500  2023-04-05        2010          160.00
4            5  350000       1800  2023-05-01        2000          194.44

In [5]:
# Date Transformation

df['date_listed'] = pd.to_datetime(df['date_listed'])

df

   property_id   price  size_sqft date_listed  year_built  price_per_sqft
0            1  250000       1500  2023-01-15        1990          166.67
1            2  300000       2000  2023-02-20        2005          150.00
2            3  150000       1200  2023-03-10        1980          125.00
3            4  400000       2500  2023-04-05        2010          160.00
4            5  350000       1800  2023-05-01        2000          194.44

In [6]:
# Extract Month

df['month'] = df['date_listed'].dt.month

df

,property_id,price,size_sqft,date_listed,year_built,price_per_sqft,month
0,1,250000,1500,2023-01-15,1990,166.67,1
1,2,300000,2000,2023-02-20,2005,150.00,2
2,3,150000,1200,2023-03-10,1980,125.00,3
3,4,400000,2500,2023-04-05,2010,160.00,4
4,5,350000,1800,2023-05-01,2000,194.44,5

In [7]:
# Outlier Detection

Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)

IQR = Q3 - Q1

outliers = df[
    (df['price'] < (Q1 - 1.5 * IQR)) |
    (df['price'] > (Q3 + 1.5 * IQR))
]

outliers

Empty DataFrame
Columns: [property_id, price, size_sqft, date_listed, year_built, price_per_sqft, month]
Index: []